# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 10, 221, 131))
        self.calendarWidget.setSelectedDate(QtCore.QDate(2024, 3, 4))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(260, 40, 111, 17))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(Form)
        self.stop.setGeometry(QtCore.QRect(260, 70, 111, 17))
        self.stop.setObjectName("stop")
        self.autostart = QtWidgets.QRadioButton(Form)
        self.autostart.setGeometry(QtCore.QRect(270, 110, 62, 14))
        self.autostart.setObjectName("autostart")
        self.video = QVideoWidget(Form)
        self.video.setGeometry(QtCore.QRect(29, 159, 341, 111))
        self.video.setObjectName("video")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start.setText(_translate("Form", "Старт"))
        self.stop.setText(_translate("Form", "Стоп"))
        self.autostart.setText(_translate("Form", "Автостарт"))
from qvideowidget import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
